apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  replicas: 3
  serviceName: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: consul
        image: consul:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - agent
        - -advertise=$(POD_IP)
        - -bind=0.0.0.0
        - -bootstrap-expect=3
        - -client=0.0.0.0
        - -disable-host-node-id
        - -domain=cluster.local
        - -raft-protocol=3
        - -server
        - -ui
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - >
                consul join \
                  consul-0.consul.$(NAMESPACE).svc.cluster.local \
                  consul-1.consul.$(NAMESPACE).svc.cluster.local \
                  consul-2.consul.$(NAMESPACE).svc.cluster.local \
                  || true
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        - name: consul-config
          mountPath: /consul/myconfig
      volumes:
      - name: consul-config
        configMap:
          name: consul-config
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi